name: FarmingPlugin
version: 1.0
main: com.noahnewmanmack.farmingplugin2.FarmingPlugin
api-version: 1.18
description: Plugin designed to recofigure Minecraft Farming by creating yield-item combinations.
author: Noah-Mack-01

commands:
  notrample:
    description: Prevent a provided username's character from trampling crops.
    usage: "Usage: /<command> <player_name>"